// images.js
export const images = {
  bgImage: require('../../assets/bgImage.png'),
  backgroundImg: require('../../assets/background.png'),
  logoIcon: require('../../assets/Logo.png'),
  NotificationIcon: require('../../assets/Notification.png'),
  UserIcon: require('../../assets/User.png'),
  sectionImage: require('../../assets/Sectionbg.png'),
  menuIcon: require('../../assets/menu.png'),
  vectorIcon: require('../../assets/Vector.png'),
  userIcon: require('../../assets/usersIcon.png'),
  IllustrationIcon: require('../../assets/Illustration.png'),
  playIcon: require('../../assets/Play.png'),
  redditIcon: require('../../assets/Artwork.png'),
  AtIcon: require('../../assets/AT.png'),
  zendeskIcon: require('../../assets/zendesk.png'),
  LinkedinIcon: require('../../assets/Linkedin.png'),
  NetflixIcon: require('../../assets/Netflix.png'),
  SignUpIcon : require('../../assets/SignUp.png'),
  TrackIcon: require('../../assets/Track.png'),
  SalesIcon: require('../../assets/Sales.png'),
  FeaturesIcon: require('../../assets/Features.png'),
 extensionIcon: require('../../assets/extension.png'),
PhoneIcon: require('../../assets/phone.png'),
StreetIcon: require('../../assets/Street.png'),
aboutIcon: require('../../assets/about.png'),
bgImage: require('../../assets/bgImage.png'),
flightLogo: require('../../assets/Flightweblogo.png'),
HotelsIcon: require('../../assets/building.png'),
HotelImage: require('../../assets/HotelImage.png'),
PlaneIcon: require('../../assets/flight.png'),
personIcon: require('../../assets/person.png'),
user: require('../../assets/UserIcon.png'),
designIcon: require('../../assets/design.png'),
CloudsIcon: require('../../assets/Clouds.webp'),
CloudsImage: require('../../assets/HeroBanner.webp'),
CallIcon: require('../../assets/Call.png'),
emailIcon: require('../../assets/Email.png'),
MediaIcon: require('../../assets/Media.png'),
FacebookIcon: require('../../assets/FaceBook.png'),
GoogleIcon: require('../../assets/Google.png'),
TwitterIcon: require('../../assets/Twitter.png'),
WifiIcon: require('../../assets/WIfI.png'),
phone: require('../../assets/phoneIcon.png'),
messageIcon: require('../../assets/mail.png'),
pinIcon: require('../../assets/pin.png'),
footerlgIcon: require('../../assets/footerlg.png'),
experienceIcon: require('../../assets/experience.png'),
agentIcon: require('../../assets/agent.png'),
TravelImage: require('../../assets/Travel.png'),
barsIcon: require('../../assets/bars.png'),
loginBg: require('../../assets/Loginbg.png'),
Google: require('../../assets/GoogleIcon.png'),
Cloudbg: require('../../assets/Cloud.png')



  };
