// images.js
export const images = {
  logoIcon: require('../../assets/Logo.png'),
  NotificationIcon: require('../../assets/Notification.png'),
  UserIcon: require('../../assets/User.png'),
  sectionImage: require('../../assets/Sectionbg.png'),
  menuIcon: require('../../assets/menu.png'),
  vectorIcon: require('../../assets/Vector.png'),
  userIcon: require('../../assets/usersIcon.png'),
  IllustrationIcon: require('../../assets/Illustration.png'),
  playIcon: require('../../assets/Play.png'),
  redditIcon: require('../../assets/Artwork.png'),
  AtIcon: require('../../assets/AT.png'),
  zendeskIcon: require('../../assets/zendesk.png'),
  LinkedinIcon: require('../../assets/Linkedin.png'),
  NetflixIcon: require('../../assets/Netflix.png'),
  SignUpIcon : require('../../assets/SignUp.png'),
  TrackIcon: require('../../assets/Track.png'),
  SalesIcon: require('../../assets/Sales.png'),
  FeaturesIcon: require('../../assets/Features.png'),
 extensionIcon: require('../../assets/extension.png'),
PhoneIcon: require('../../assets/phone.png'),
StreetIcon: require('../../assets/Street.png'),

  };
